version: '3.8'

services:
  script_chargement_donnnees:
    build: ./script
    container_name: script_chargement_donnnees
    restart: unless-stopped
    volumes:
      - /home/projet_bigdata/env:/app/env:ro  
      - /home/projet_bigdata/logs:/var/logs
    environment:
      - ENV_PATH=/app/env/.env  
