version: '3.8'

services:
  script_chargement_donnnees:
    build: ./script
    container_name: script_chargement_donnnees
    restart: unless-stopped
    volumes:
      - /home/projet_bigdata/env:/app/env:ro 
    environment:
      - ENV_PATH=/app/env/.env  
    networks:
      - ml_net

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    restart: unless-stopped
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri file:/mlruns
      --default-artifact-root file:/mlruns
      --allowed-hosts "*"
    expose:
      - "5000"
      - "6767"
    volumes:
      - /home/projet_bigdata/mlflow/mlruns:/mlruns
    networks:
      - ml_net
      - proxy_net
  
  trainer:
    build: ./mlfolder
    container_name: trainer
    restart: unless-stopped
    volumes:
      - /home/projet_bigdata/mlflow/state:/state
      - /home/projet_bigdata/mlflow/mlruns:/mlruns
      - /home/projet_bigdata/env:/app/env:ro 
    environment:
      - ENV_PATH=/app/env/.env  
    depends_on:
      - mlflow
    networks:
      - ml_net


  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    expose:
      - 6767
    depends_on:
      - script_chargement_donnnees
      - trainer
    networks:
      - ml_net
      - proxy_net

networks:
  ml_net:
    driver: bridge
  proxy_net:
    external: true